<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-SAPG2265" failures="1" tests="4" name="Personal Loan" time="0.054" errors="0" timestamp="2022-08-16T22:33:04 IST">
  <testcase classname="testPackage.Day1" name="secondDemo" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testPackage.Day1.secondDemo(Day1.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- secondDemo -->
  <testcase classname="testPackage.Day2" name="pLoan" time="0.001"/>
  <testcase classname="testPackage.Day4" name="mobileLoginHomeLoan" time="0.002"/>
  <testcase classname="testPackage.Day4" name="webLoginHomeLoan" time="0.001"/>
  <testcase classname="testPackage.Day4" name="loginAPIHomeLoan" time="0.0">
    <ignored/>
  </testcase> <!-- loginAPIHomeLoan -->
  <testcase classname="testPackage.Day1" name="demo" time="0.0">
    <ignored/>
  </testcase> <!-- demo -->
</testsuite> <!-- Personal Loan -->
